### ISSUE TITLE
Build for ESP32-S3 devkit

### ISSUE THREAD

**Issue by fathanpranaya** [YOGYUI/matter-esp32-ekmc16#1]
hi. thanks for sharing your awesome project. I have a question, can this project also be built for ESP32S3? if so, could you give the step how to do that?

**Comment by YOGYUI** [comment]
@fathanpranaya Hi, thanks for your interest.
If you want to build with esp32s3 soc, 2 steps should be taken I guess.
1. Modify CMakeLists.txt
```
# set(ENV{ESP_MATTER_DEVICE_PATH} $ENV{ESP_MATTER_PATH}/device_hal/device/esp32_devkit_c)
set(ENV{ESP_MATTER_DEVICE_PATH} $ENV{ESP_MATTER_PATH}/device_hal/device/esp32s3_devkit_c)
```
2. prepare build environment for specific platform using idf.py
```
$ idf.py set-target esp32s3
```

Take a try and let me know whether it works :)

**Comment by fathanpranaya** [comment]
thank you for the quick response. I followed your steps, and it works. thanks~
